#!/bin/bash

set -x 
rm -rf build
mkdir build
mkdir build/IPIP_Scorer
pkg -t node10-macos-x64 --output build/IPIP_Scorer/IPIP-Scorer cli.js
cp -r node_modules/puppeteer/.local-chromium/ build/IPIP_Scorer/chromium
cd build
zip --quiet -r IPIP_Scorer.zip IPIP_Scorer
cd ..
